# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7461bbf38dbf2f796ab609ff96a1bbeb0540fc3f05968236585c86dd40646310b437b880fedbf2e08f7206ffc2b4b3f02f4c9e82feff5643a812957e1bcc69af

test:
  secret_key_base: 2e36ab8bea02787959b375407c7869ebc70b4af6a10d50774bbe7075a1343d40c5e5288d5fd66519b613daff9012987ba8c4094c2a30ad8e05eeee4cd8391438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
